### PR TITLE
Add MerchantExpanse

### PR DESCRIPTION
**Pull request by Oronar**
[MerchantExpanse](https://github.com/Oronar/MerchantExpanse) is a .NET 5 API wrapper. The repo now contains some instructions on how to install the nuget package and a basic example project to demonstrate its use.

### CODE REVIEW

**Comment by jadlers** [comment]
The changes looks good! My only problem, and it's completely on me not you is my unfamiliarity with .NET. I've personally tested to follow the instructions to get the project up and running locally before I merge any requests. Does any of the @SpaceTradersAPI/collaborators have more experience and could help to test it out? Or would @Oronar mind to help me set up for testing locally?

**Comment by jadlers** [comment]
Sorry for the ping collaborators! I misunderstood who that tag referred to. I meant to ping the collaborators of _this_ repository. @HamishWHC & @HOWZ1T , do you have any experience in working with .NET?

**Comment by Oronar** [comment]
Sure I can help out. Ping me on discord if you need specifics.

If you already have a preferred IDE than all you really need is the [.NET SDK](https://dotnet.microsoft.com/download). Otherwise I'd suggest [VS Code](https://code.visualstudio.com/), I like using VS2019 for dotnet projects but it's a large install just to test this out.

This guide does a better job than I can of explaining the basics (ignore the F# part). https://code.visualstudio.com/docs/languages/dotnet

If you start a new project I added an example to the MerchantExapnse readme on how to install  a package using `dotnet`. But you can also just open the example project in MerchantExpanse, it already has the dependency and will install it when you run `dotnet run`

**Comment by jadlers** [comment]
Thank you very much for the time you put into helping me testing it out. I've understood that the requirement of testing out if projects work in order for them to be approved on this list can be tricky at times. Anyhow, I got a development setup and I'm satisfied. Let's get your project on the list!

**Pull request merged**
